### ISSUE TITLE
11.0.5 - Issue when commit is not required

### ISSUE THREAD

**Issue by antoinekh** [PaloAltoNetworks/pan-os-python#569]
## Describe the bug

With Ansible, when I commit to Panorama I have this issue. This is related to the pan-os-python as 
```
 FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/panos/base.py\", line 4899, in _commit\n    jobid = commit_response.find(\"./result/job\").text\nAttributeError: 'NoneType' object has no attribute 'text'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1719842067.2051706-209-234579401563979/AnsiballZ_panos_commit_panorama.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1719842067.2051706-209-234579401563979/AnsiballZ_panos_commit_panorama.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1719842067.2051706-209-234579401563979/AnsiballZ_panos_commit_panorama.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_panorama', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_panorama', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_panorama_payload_3b6gz7wk/ansible_paloaltonetworks.panos.panos_commit_panorama_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_panorama.py\", line 222, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_panorama_payload_3b6gz7wk/ansible_paloaltonetworks.panos.panos_commit_panorama_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_panorama.py\", line 200, in main\n  File \"/usr/local/lib/python3.9/site-packages/panos/base.py\", line 4803, in commit\n    return self._commit(\n  File \"/usr/local/lib/python3.9/site-packages/panos/base.py\", line 4906, in _commit\n    commit_response_msg = commit_response.find(\"./msg/line\").text\nAttributeError: 'NoneType' object has no attribute 'text'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
```
## Expected behavior

It should work with a message Commit not needed

No issues when modification are there to commit

## Current behavior

Python error 

```
 commit_response_msg = commit_response.find(\"./msg/line\").text\nAttributeError: 'NoneType' object has no attribute 'text'\n",
```

## Possible solution

Change line on /panos/base.py (https://github.com/PaloAltoNetworks/pan-os-python/blob/62bcff3bca86a5ff745eae3e92635d109673963a/panos/base.py#L4906C1-L4906C78)

to add a try except

```
except AttributeError:
            if exception:
                raise err.PanCommitNotNeeded("Commit not needed", pan_device=self)
```
## Steps to reproduce

1. Commit without changes
2.

## Context

Was working fine before version 11.x

## Your Environment

Last version of

**Comment by antoinekh** [comment]
Maybe similar to #471

**Comment by antoinekh** [comment]
I have tried with success to add the following lines and this fix the issue

L4906 on base.py
```
    try:
        commit_response_msg = commit_response.find("./msg/line").text
    except AttributeError:
        commit_response_msg = "No message in commit response"
    self._logger.debug("No job id. Msg: " + commit_response_msg)
```

**Comment by antoinekh** [comment]
the problem has been added here  #493

**Comment by antoinekh** [comment]
Pull request #557

**Comment by antoinekh** [comment]
I can confirm that it works in pan-os-python 1.11.0

**Comment by mhca99** [comment]
was that fixed?  I still have issue with following environment:
```
pan-os-python 1.12.1
pan-python    0.17.0
pandevice     0.14.0
ansible core  2.18.4
python version  3.12.3
```

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'text'
fatal: [myhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/auser/panos_venv/lib/python3.12/site-packages/panos/base.py\", line 4901, in _commit\n    jobid = commit_response.find(\"./result/job\").text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'text'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/auser/.ansible/tmp/ansible-tmp-1744567839.807405-32835-268815853610618/AnsiballZ_panos_commit_panorama.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/auser/.ansible/tmp/ansible-tmp-1744567839.807405-32835-268815853610618/AnsiballZ_panos_commit_panorama.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/auser/.ansible/tmp/ansible-tmp-1744567839.807405-32835-268815853610618/AnsiballZ_panos_commit_panorama.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_panorama', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_commit_panorama', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_panorama_payload_iodd6thy/ansible_paloaltonetworks.panos.panos_commit_panorama_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_panorama.py\", line 222, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_commit_panorama_payload_iodd6thy/ansible_paloaltonetworks.panos.panos_commit_panorama_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_commit_panorama.py\", line 200, in main\n  File \"/home/auser/panos_venv/lib/python3.12/site-packages/panos/base.py\", line 4805, in commit\n    return self._commit(\n           ^^^^^^^^^^^^^\n  File \"/home/auser/panos_venv/lib/python3.12/site-packages/panos/base.py\", line 4908, in _commit\n    commit_response_msg = commit_response.find(\"./msg/line\").text\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'text'\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}
